version: '3.8'

services:
  db:
    image: postgres:14
    ports:
      - "5433:5432" # Changed host port to 5433 to avoid conflict
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: carbon_db
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - "3001:3001"
    environment:
      DB_HOST: db
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: carbon_db
      DB_PORT: 5432
    command: npm run dev

volumes:
  pgdata:
